- Sources/Fullscreen/MotorTransactionInsuranceConfirmationView/MotorTransactionInsuranceConfirmationView.swift
- Each tap on the button triggers a new request of purchasing insurance. The request takes a couple of seconds to process and causes some frustration to the user which ends up tapping it multiple times.
- Disable insurance confirmation button after tapping it once.
Minor change
> Disable insurance confirmation button after tap

- .gitignore
- Package.resolved
- Package.swift
- Workspace/FinnUIDemo.xcworkspace/xcshareddata/swiftpm/Package.resolved
In order to include this repo in SearchQuest I need it to depend on the same version of FinniversKit as SearchQuest.
- Bumped to 81.0.0
Minor
None
> Bump FinniversKit to 81.0.0

- FinnUI.podspec
- Sources/Fullscreen/ExploreDetail/ExploreDetailView.swift
- Sources/Fullscreen/ExploreDetail/Helpers/ExploreDetailLayoutBuilder.swift
- Sources/Fullscreen/ExploreDetail/Helpers/NSCollectionLayoutSection+Staggered.swift
There is room to show 3 column grid on iPad.
- Ads section: show 3 column grid on iPad
- Collections section: always show one row carousel on iPad
Patch change.
| Before | After |
| --- | --- |
| <img width="869" alt="Screenshot 2021-06-25 at 12 24 24" src="https://user-images.githubusercontent.com/10529867/123411032-4ac02980-d5b0-11eb-881b-dd3f307ad67c.png"> | <img width="868" alt="Screenshot 2021-06-25 at 12 23 37" src="https://user-images.githubusercontent.com/10529867/123410936-2c5a2e00-d5b0-11eb-825b-f288f5f1ef3f.png"> |
> Explore detail: iPad support

- Sources/Extensions/Foundation/ArrayExtensions.swift
- Sources/Fullscreen/Explore/ExploreView.swift
Was able to produce a crash when leaving the view before everything had loaded.
- Make sure the sectionIndex is valid before using it (in the crash situation we got sectionIndex 0 but had no sections yet).
- Added ArrayExtensions so that is easy to do with the `array[safe: x]`.
Minor / patch
> Fix crash when using ExploreView

- Sources/Fullscreen/Explore/ExploreView.swift
- Sources/Fullscreen/ExploreDetail/ExploreDetailView.swift
There is a way to make the ExploreDetailView crash that needs to be fixed. Same as was fixed for ExploreView in https://github.com/finn-no/finnui-ios/pull/24
Make sure the sectionIndex is valid before using it (in the crash situation we got sectionIndex 0 but had no sections yet).
Patch
> Fix crash when using ExploreDetailView

- Demo/SnapshotTests/SwiftUIViewTests.swift
- Demo/Sources/AppDelegate.swift
- Demo/Sources/Demo/DemoHelpers.swift
- Demo/Sources/Demo/DemoViews/SwiftUIDemoViews.swift
- Demo/Sources/Demo/DemoViewsTableViewController.swift
- Demo/Sources/Demo/Helpers.swift
- Demo/Sources/Demo/NavigationController.swift
- Demo/Sources/Extensions/UIKit/UITraitCollection+Extensions.swift
- Demo/Sources/SwiftUI/BapAdView+Previews.swift
- Sources/AdView/BapAdView/BapAdView.swift
- Sources/AdView/Components/AuthorView/AuthorView.swift
- Sources/AdView/Components/AuthorView/SingleImageProvider.swift
- Sources/AdView/Components/DescriptionView/DescriptionView.swift
- Sources/AdView/Components/ImageGalleryView/CollectionImageProvider.swift
- Sources/AdView/Components/ImageGalleryView/ImageGalleryView.swift
- Sources/AdView/Components/PagerView.swift
- Sources/AdView/Components/PhoneNumberView/PhoneNumberView.swift
- Sources/AdView/Components/TryHeltHjemView/TryHeltHjemView.swift
- Sources/Base Components/ButtonStyle+Previews.swift
- Sources/Extensions/SwiftUI/ImageExtensions.swift
- Sources/Extensions/UIKit/UITraitCollectionExtensions.swift
- Sources/Fullscreen/Settings/Foundation/Modifiers/Appearance.swift
- Sources/Fullscreen/Settings/Foundation/Modifiers/BottomDividerModifier.swift
- Sources/Fullscreen/Settings/Foundation/Views/BasicListCell.swift
- Sources/Fullscreen/Settings/Foundation/Views/BasicListCellWrapper.swift
- Sources/Fullscreen/Settings/SettingsView.swift
Pre iOS 13 is no longer supported.
Remove a lot of checks if iOS 13 is available, we do not need that anymore.
Framework is already marked as min iOS 13 so this is a cosmetic change that has no effect at all on the produced binary.
> Remove checks if iOS 13 is available

- Demo/Sources/Demo/BaseDemoViewController.swift
- Demo/Sources/Fullscreen/Stories/StoryDemoView.swift
- Sources/Fullscreen/Stories/StoriesView.swift
- Sources/Fullscreen/Stories/Subviews/StoryCollectionViewCell.swift
Adding a few extra features to stories. This PR will be merged into #38   
- Tracking support: We let the delegate know about a few different ways stories have ended (`EndStoryAction`), in order to track these events.
- Always bounce horizontal - so it's possible to swipe to dismiss a story even if there's only 1 story cell
- Insert placeholder image for search icon
None.
> Stories: Tracking support, always swipeable, placeholder image

- Sources/Components/TagCloudGridView/Cell/TagCloudCellViewModel.swift
- Sources/Fullscreen/Explore/ViewModels/ExploreCollectionViewModel.swift
- Sources/Fullscreen/Explore/ViewModels/ExploreSectionViewModel.swift
- Sources/Fullscreen/ExploreDetail/ViewModels/ExploreAdCellViewModel.swift
- Sources/Fullscreen/ExploreDetail/ViewModels/ExploreDetailViewModel.swift
- Sources/Helpers/UniqueHashableItem.swift
After switching to a new backend, we got crash reports about non-unique section identifiers in explore snapshots:
`Fatal: supplied section identifiers are not unique. Duplicate identifiers: {( FinnUI.ExploreSectionViewModel ...`
We shouldn't crash when this happens. Therefore we won't rely on unique sections or items from the backend anymore.
Make `UniqueHashableItem`, an implementation of `Hashable` that should always be unique using `UUID`.
Use it for all sections and items in explore snapshots.
Patch.
Might affect animations a bit.
> Explore crash fix: Make all snapshot sections and items unique

- Sources/Recycling/PromotedCells/PromotedRealestateCellView.swift
- Sources/Recycling/PromotedCells/PromotedRealestateCellViewModel.swift
- Workspace/FinnUIDemo.xcworkspace/xcshareddata/swiftpm/Package.resolved
We need a sold ribbon on real estate highlight listing cells.
Add optional `ribbonText` to view model.
If it's present, insert a `RibbonView` with that text.
Just a patch.
See "Solgt" ribbon, otherwise no changes.
> Highlight listing: Add ribbon - to be used for sold units

- Demo/Demo.xcodeproj/project.pbxproj
- Demo/SnapshotTests/XCTestCastExtensions.swift
- Workspace/FinnUIDemo.xcworkspace/xcshareddata/swiftpm/Package.resolved
This PR contains the same change as in https://github.com/finn-no/FinniversKit/pull/1094.
- Point SnapshotTesting to [pimms/swift-snapshot-testing](https://github.com/pimms/swift-snapshot-testing).
- Set subpixelThreshold to 5.
Minor. No breaking changes.
_No UI._
> Fix: Support for snapshot tests on Intel and M1

- Sources/Recycling/PromotedCells/PromotedRealestateCellView.swift
- Sources/Recycling/PromotedCells/PromotedRealestateCellViewModel.swift
We are adding support for highlight listing for nybygg. The data inserted into the cell is a bit different, so adjusting it a bit.
- Hide labels also if text is empty String - since we get less spacing when the label is hidden
- Configure with a RibbonViewModel, so we can support different kinds of ribbon style ("Kommer for salg" for nybygg)
Breaking
"Kommer for salg" ribbon
> Highlight listing: Style ribbons and spacing adjustments 

- Demo/Sources/Components/Fiks Ferdig/FiksFerdigPriceView/FiksFerdigPriceDemoView.swift
- Sources/Components/Fiks Ferdig/FiksFerdigPriceView/FiksFerdigPriceView.swift
- Sources/Components/Fiks Ferdig/FiksFerdigPriceView/FiksFerdigPriceViewModel.swift
- Sources/Extensions/Foundation/String+Exts.swift
Updating `Label`'s `attributedText` resulted some weird layout issues in the FINN app when we used `FiksFerdigPriceView`.
The attributed string creation was moved to the view model.
Minor: The view model was extended by a property.
> Fix fiksferdig priceview

- Sources/Components/Fiks Ferdig/FiksFerdigPriceView/FiksFerdigPriceView.swift
The fiks ferdig price view has to be changed according to UI and API specifications.
We don't have to display the shipping information when the price is not sepcified.
Minor: Only the look is changing.
| Before | After |
| --- | --- |
| ![Simulator Screen Shot - iPhone 14 Pro - 2022-11-08 at 13 16 54](https://user-images.githubusercontent.com/5146034/200561593-aea1879c-d82e-46f7-8d55-7649d26b249b.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2022-11-08 at 13 16 28](https://user-images.githubusercontent.com/5146034/200561653-c9924d9f-98bd-45b1-8a55-7e847d61325d.png) |
> Update fiks ferdig price view.

- Sources/Fullscreen/ExploreDetail/Helpers/NSCollectionLayoutSection+Staggered.swift
Accessibility changes so low vision users will have an easier time.
Single column for collections scrolling. Double column for iPad, scaled down from the 3 default columns
minor
this video shows old and new layouts. (Includes changes to FinniversKit as well.)
https://user-images.githubusercontent.com/17337441/212094921-de66406a-fee4-4e92-b167-70d151b8ef90.mov
> set 1 column for when accessibility text size is enabled. 2 for ipad

- Sources/Fullscreen/Explore/Helpers/ExploreLayoutBuilder.swift
Noticed the image heights were a bit off in Explore recommendations. The aspect ratio is the opposite of what it should be.
Change so aspect ratio is calculated by width/height, instead of height/width.
Patch.
| Before | After |
| --- | --- |
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-01-20 at 09 05 16](https://user-images.githubusercontent.com/17450858/213647677-ed46297a-10b6-484a-bfd9-87ea6abdc468.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-01-20 at 09 04 45](https://user-images.githubusercontent.com/17450858/213647657-eb245788-708e-4525-bc81-0e0e8626457d.png) |
> Explore recommendations: Fix aspect ratio for correct image heights

- Sources/Fullscreen/Explore/ViewModels/ExploreRecommendationAdViewModel.swift
This is to help us support "Fiks ferdig" badges on recommendations in explore.
Feed in `BadgeViewModel` (optional) to `ExploreRecommendationAdViewModel`
Patch, since default is nil.
This is how it will look once used.
> Add badge to explore recommendations view model

- Sources/Components/Fiks Ferdig/FiksFerdigContactSellerView/FiksFerdigContactSellerView.swift
The border color in `FiksFerdigContactSellerView` were set in `setup()`, which doesn't get updated when/if changing to dark mode.
- Set `borderColor` in `layoutSubviews()`
Patch.
_None._
> Fix: Set borderColor in layoutSubviews

- Sources/Fullscreen/Explore/ExploreView.swift
When making changes to the structure in section and how we configure ExploreView with recommendations we accidentally set the title of the recommendations section to the title of the first item in the recommendations list. 
Fixed the title
Patch
> Fixed recommendation section title bug

- Sources/Components/Fiks Ferdig/FiksFerdigPriceView/FiksFerdigPriceView.swift
- Sources/Components/Fiks Ferdig/FiksFerdigPriceView/FiksFerdigPriceViewModel.swift
The Fiks Ferdig price label had the wrong accessibility label for the price.
Set correct price and shipping accessibility labels.
Patch.
> Fix wrong Fiks Ferdig price label accessibility text.

- Package.swift
To avoid having to update a lot of repositories every time one of the base building blocks change major version.
Expect FinniversKit to not break anything used by FinnUI (and if it is something breaking that there will also be a change here).
Minor
> Expect all future FinniversKit versions to also work

- Sources/Components/Fiks Ferdig/FiksFerdigInfoView/FiksFerdigShippingInfoCell.swift
- Sources/Components/Fiks Ferdig/FiksFerdigInfoView/FiksFerdigShippingInfoCellViewModel.swift
The shipping provider UI needs to work regardless of shipping provider ID.
Moved to struct for shipping provider ID so we can handle future shipping providers.
Minor, backwards compatible.
> TJT-2205 ShippingInfo providers

- Sources/Extensions/Foundation/Array+Extensions.swift
- Sources/Fullscreen/Explore/ExploreView.swift
There's a bug in the recommendations backend that causes duplicate recommendations. When this happens, the explore view (i.e. the reCommerce or jobs market front page) crashes with an `NSInternalInconsistencyException`. We should probably handle this, even if it's a bug on the backend side.
Filter out duplicate recommendation items before appending them to the explore view.
Patch
> Fix crash on duplicate recommendations in explore view

- Sources/Fullscreen/Explore/ExploreView.swift
I missed a spot in #127 
Filter out duplicate recommendation items in loadMoreRecommendations.
Patch
> Fix crash on duplicate recommendations in loadMoreRecommendations

- Sources/Fullscreen/Explore/ExploreView.swift
- Sources/Fullscreen/Explore/ViewModels/ExploreRecommendationAdViewModel.swift
Filtering for unique caused an issue where certain ads weren't tappable because mismatching indeces. 
Hash ads based on a unique (per object) id instead of their ad id.
Patch
> Remove unique filtering on recommendations in explore view
